FROM armhf/ubuntu:14.04
MAINTAINER bg.chun@samsung.com

COPY libs /libs
COPY publisher publisher
COPY subscriber subscriber
COPY samples/sample_data_model.aml sample_data_model.aml
COPY run.sh run.sh
CMD ["./run.sh", "arg1", "arg2"]
