FROM docker.sec.samsung.net:5000/edge/base-image:latest AS build
MAINTAINER bg.chun@samsung.com

COPY ./samples/build/qemu-arm-static /usr/bin/qemu-arm-static

RUN mkdir /root/.ssh/
COPY ./samples/build/id_rsa /root/.ssh/id_rsa
COPY ./samples/build/id_rsa.pub /root/.ssh/id_rsa.pub
COPY ./samples/build/known_hosts /root/.ssh/known_hosts

RUN chmod 600 /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa.pub
COPY samples/build/SRnD+Web+Proxy.crt /usr/local/share/ca-certificates/SRnD+Web+Proxy.crt
COPY samples/build/SRnD+Web+Proxy.crt /root

RUN apt-get update && apt-get install -y vim \
    apt-transport-https \
    ca-certificates \
    software-properties-common \
    git \
    python \
    python-six \
    python-software-properties
RUN update-ca-certificates

RUN add-apt-repository ppa:ubuntu-toolchain-r/test
RUN apt-get install -y gcc-5 g++-5
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 1

RUN add-apt-repository ppa:george-edison55/cmake-3.x && apt-get update
RUN apt-get install -y autoconf automake make unzip sudo autogen libtool pkg-config scons cmake python-dev wget

#build protocol-ezmq-plus-cpp
WORKDIR /
RUN git clone git@github.sec.samsung.net:RS7-EdgeComputing/protocol-ezmq-plus-cpp.git
WORKDIR /protocol-ezmq-plus-cpp
RUN sh build_arm.sh --with_dependencies=false --build_mode=release
RUN sh install_arm.sh

# create real image
FROM docker.sec.samsung.net:5000/edge/base-image:latest
WORKDIR /

#copy lib from build
COPY --from=build /protocol-ezmq-plus-cpp/out/linux/armhf/release/libezmq_plus.so /usr/local/lib/libezmq_plus.so

#copy samples from build
COPY --from=build /protocol-ezmq-plus-cpp/out/linux/armhf/release/samples/publisher /publisher
COPY --from=build /protocol-ezmq-plus-cpp/out/linux/armhf/release/samples/AmlSubscriber /AmlSubscriber
COPY --from=build /protocol-ezmq-plus-cpp/out/linux/armhf/release/samples/XmlSubscriber /XmlSubscriber
COPY --from=build /protocol-ezmq-plus-cpp/out/linux/armhf/release/samples/TopicDiscovery /TopicDiscovery
COPY --from=build /protocol-ezmq-plus-cpp/samples/sample_data_model.aml /sample_data_model.aml
COPY --from=build /protocol-ezmq-plus-cpp/run.sh /run.sh

CMD ["./run.sh", "arg1", "arg2", "arg3"]
