###############################################################################
# Copyright 2018 Samsung Electronics All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
###############################################################################


################ EZMQ Plus sample build script ##################
Import('env')

target_os = env.get('TARGET_OS')
ezmq_plus_sample_env = env.Clone()

######################################################################
# Build flags
######################################################################
ezmq_plus_sample_env.AppendUnique(CPPPATH=[
    '/usr/local/include',
    '/usr/local/include/curl',
    '/usr/local/include/datamodel-aml-cpp',
    '/usr/local/include/protocol-ezmq-cpp',
    '/usr/local/include/protocol-ezmq-plus-cpp',
    '../dependencies/protocol-ezmq-cpp/include',
    '../dependencies/protocol-ezmq-cpp/extlibs/zmq',
    '../dependencies/protocol-ezmq-cpp/protobuf',
    '../dependencies/datamodel-aml-cpp/include',
    '../include'
])

ezmq_plus_sample_env.AppendUnique(
    CXXFLAGS=['-O2', '-g', '-Wall', '-fmessage-length=0', '-std=c++11', '-I/usr/local/include'])

ezmq_plus_sample_env.AppendUnique(LIBS=['aml', 'ezmq_plus'])

####################################################################
# Source files and Targets
######################################################################
ezmqxPublisher = ezmq_plus_sample_env.Program('publisher', 'publisher.cpp')
ezmqxAmlSubscriber = ezmq_plus_sample_env.Program('AmlSubscriber', 'AmlSubscriber.cpp')
ezmqxXmlSubscriber = ezmq_plus_sample_env.Program('XmlSubscriber', 'XmlSubscriber.cpp')
ezmqxTopicDiscovery = ezmq_plus_sample_env.Program('TopicDiscovery', 'TopicDiscovery.cpp')
ezmqxSecuredPublisher = ezmq_plus_sample_env.Program('securedPublisher', 'securedPublisher.cpp')
ezmqxSecuredAmlSubscriber = ezmq_plus_sample_env.Program('SecuredAmlSubscriber', 'SecuredAmlSubscriber.cpp')