################ EZMQ Plus sample build script ##################
Import('env')

target_os = env.get('TARGET_OS')
ezmq_plus_sample_env = env.Clone()

######################################################################
# Build flags
######################################################################
ezmq_plus_sample_env.AppendUnique(CPPPATH=[
	'../dependencies/protocol-ezmq-cpp/include',
    '../dependencies/protocol-ezmq-cpp/extlibs/zmq',
    '../dependencies/protocol-ezmq-cpp/protobuf',
    '../dependencies/datamodel-aml-cpp/include',
    '../include'
])

ezmq_plus_sample_env.AppendUnique(
    CXXFLAGS=['-O2', '-g', '-Wall', '-fmessage-length=0', '-std=c++11', '-I/usr/local/include'])

ezmq_plus_sample_env.AppendUnique(LIBS=['aml', 'ezmq_plus'])

####################################################################
# Source files and Targets
######################################################################
ezmqxPublisher = ezmq_plus_sample_env.Program('publisher', 'publisher.cpp')
ezmqxAmlSubscriber = ezmq_plus_sample_env.Program('AmlSubscriber', 'AmlSubscriber.cpp')
ezmqxXmlSubscriber = ezmq_plus_sample_env.Program('XmlSubscriber', 'XmlSubscriber.cpp')
ezmqxTopicDiscovery = ezmq_plus_sample_env.Program('TopicDiscovery', 'TopicDiscovery.cpp')
