################ EZMQ Plus sample build script ##################
Import('env')

gtest_env = SConscript('#extlibs/gtest/SConscript')
lib_env = gtest_env.Clone()
ezmq_plus_unittest_env = lib_env.Clone()
target_os = ezmq_plus_unittest_env.get('TARGET_OS')

######################################################################
# Build flags
######################################################################
ezmq_plus_unittest_env.AppendUnique(CPPPATH=[
    '/usr/local/include',
    '/usr/local/include/curl',
    '/usr/local/include/datamodel-aml-cpp',
    '/usr/local/include/protocol-ezmq-cpp',
	  '../dependencies/protocol-ezmq-cpp/include',
    '../dependencies/protocol-ezmq-cpp/extlibs/zmq',
    '../dependencies/protocol-ezmq-cpp/protobuf',
    '../dependencies/datamodel-aml-cpp/include',
    '../extlibs/gtest/googletest-release-1.8.0/googletest/include/gtest',
    '../extlibs/gtest/googletest-release-1.8.0/googlemock/include/gmock',
    '../include',
    '../internal',
    '../internal/fake',
    '../internal/logger',
    './'
])

ezmq_plus_unittest_env.AppendUnique(
    CXXFLAGS=['-O2', '-g', '-Wall', '-fmessage-length=0', '-std=c++11', '-I/usr/local/include'])

ezmq_plus_unittest_env.AppendUnique(LIBPATH=[lib_env.get('BUILD_DIR')])

ezmq_plus_unittest_env.AppendUnique(LIBS=['aml', 'ezmq_plus', 'gmock'])

if target_os in ['linux']:
   if not env.get('RELEASE'):
       ezmq_plus_unittest_env.AppendUnique(CCFLAGS=['-g'])
       ezmq_plus_unittest_env.PrependUnique(LIBS=['gcov'])
       ezmq_plus_unittest_env.AppendUnique(CXXFLAGS=['--coverage'])
       ezmq_plus_unittest_env.AppendUnique(CPPDEFINES=['DEBUG_LOG'])

####################################################################
# Source files and Targets
######################################################################
ezmqx_config_test = ezmq_plus_unittest_env.Program('ezmqx_config_test', 'ezmqx_config_test.cpp')
ezmqx_publisher_test = ezmq_plus_unittest_env.Program('ezmqx_publisher_test', 'ezmqx_publisher_test.cpp')
ezmqx_subscriber_test = ezmq_plus_unittest_env.Program('ezmqx_subscriber_test', 'ezmqx_subscriber_test.cpp')
ezmqx_topicdiscovery_test = ezmq_plus_unittest_env.Program('ezmqx_topicdiscovery_test', 'ezmqx_topicdiscovery_test.cpp')
ezmqx_topicvalidate_test = ezmq_plus_unittest_env.Program('ezmqx_topicvalidate_test', 'ezmqx_topicvalidate_test.cpp')